/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Point;
import java.time.LocalDate;

import Vehicule.Voiture;

/**
 *
 * @author Skylli
 */
public class ajoutVehiculeDlg extends javax.swing.JDialog {

    /**
     * Creates new form ajoutVehicule2
     */
    public ajoutVehiculeDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Point p = parent.getLocation();
        
        getContentPane().setLocation(p);
    }
    
    private Voiture v;
    
    public Voiture getVoiture(){return v;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        marqueLabel = new javax.swing.JLabel();
        modeleLabel = new javax.swing.JLabel();
        immatriculationLabel = new javax.swing.JLabel();
        circulDateLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        marqueField = new javax.swing.JTextField();
        modeleField = new javax.swing.JTextField();
        immatriculationField = new javax.swing.JTextField();
        circulDateField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        validerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        marqueLabel.setText("Marque :");
        jPanel1.add(marqueLabel);

        modeleLabel.setText("Modèle :");
        jPanel1.add(modeleLabel);

        immatriculationLabel.setText("Immatriculation :");
        jPanel1.add(immatriculationLabel);

        circulDateLabel.setText("1er mise en circulation (yyyy-mm-dd)");
        jPanel1.add(circulDateLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));
        jPanel2.add(marqueField);
        jPanel2.add(modeleField);
        jPanel2.add(immatriculationField);
        jPanel2.add(circulDateField);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        validerButton.setText("Valider");
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });
        jPanel3.add(validerButton);

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });
        jPanel3.add(annulerButton);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
        // TODO add your handling code here:
//    	String marque = marqueField.getText();
//    	String modele = modeleField.getText();
//    	String immat = immatriculationField.getText();
//    	LocalDate premCircul = LocalDate.parse(circulDateField.getText()); 
//    	
//    	v = new Voiture(marque, modele, immat, premCircul);
    	v = new Voiture();
    	this.setVisible(false);
        dispose();
    	System.out.println("yolo");
        
    }//GEN-LAST:event_validerButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutVehiculeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutVehiculeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutVehiculeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutVehiculeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ajoutVehiculeDlg dialog = new ajoutVehiculeDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JTextField circulDateField;
    private javax.swing.JLabel circulDateLabel;
    private javax.swing.JTextField immatriculationField;
    private javax.swing.JLabel immatriculationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField marqueField;
    private javax.swing.JLabel marqueLabel;
    private javax.swing.JTextField modeleField;
    private javax.swing.JLabel modeleLabel;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
